### PR TITLE
Add Tolerances to joint/cartesian waypoint XML

### PR DESCRIPTION
**Pull request by mpowelson**
Tolerances were added to the JointWaypoint and CartesianWaypoint a while back, but they were not added to the XML serialization. This adds serialization for them.

### CODE REVIEW

**Comment by Levi-Armstrong** [comment]
Looks good. Is there a unit test that confirms the serialization is working?

**Comment by mpowelson** [comment]
I changed one of the waypoints in the test to a joint waypoint so that it gets tested too. However, the serialization tests don't really test much. They just test that a composite remains the same size after serializing and deserializing. They don't actually test for correctness. I have run the serialization locally and it seems correct, but I did not try deserialization outside of the unit test.

We definitely need to improve this area of our test coverage. What would you think about adding an equality operator to the command language classes and using that in the tests?

**Comment by Levi-Armstrong** [comment]
> We definitely need to improve this area of our test coverage. What would you think about adding an equality operator to the command language classes and using that in the tests?

Sounds good to me.

**Comment by mpowelson** [comment]
@Levi-Armstrong This is ready for review.

**Comment by mpowelson** [comment]
@Levi-Armstrong Does the docker have a different version of Eigen from the system version? The unit tests all pass on my local Focal machine.

**Comment by Levi-Armstrong** [comment]
Example YAML to create a similar structure for xml.

```
namespace YAML
{

template <>
struct convert<Eigen::Isometry3d>
{
  static Node encode(const Eigen::Isometry3d& rhs)
  {
    Node xyz;
    xyz["x"] = rhs.translation().x();
    xyz["y"] = rhs.translation().y();
    xyz["z"] = rhs.translation().z();

    const Eigen::Quaterniond q(rhs.linear());
    Node quat;
    quat["x"] = q.x();
    quat["y"] = q.y();
    quat["z"] = q.z();
    quat["w"] = q.w();

    Node node;
    node["position"] = xyz;
    node["orientation"] = quat;

    return node;
  }

  static bool decode(const Node& node, Eigen::Isometry3d& rhs)
  {
    Eigen::Vector3d xyz;
    xyz.x() = node["position"]["x"].as<double>();
    xyz.y() = node["position"]["y"].as<double>();
    xyz.z() = node["position"]["z"].as<double>();

    Eigen::Quaterniond quat;
    quat.x() = node["orientation"]["x"].as<double>();
    quat.y() = node["orientation"]["y"].as<double>();
    quat.z() = node["orientation"]["z"].as<double>();
    quat.w() = node["orientation"]["w"].as<double>();

    Eigen::Isometry3d out = Eigen::Isometry3d::Identity();
    out.translation() = xyz;
    out.linear() = quat.toRotationMatrix();
    rhs = out;
    return true;
  }
};
```

**Comment by mpowelson** [comment]
> @Levi-Armstrong Does the docker have a different version of Eigen from the system version? The unit tests all pass on my local Focal machine.

This requires [Tesseract PR 549](https://github.com/ros-industrial-consortium/tesseract/pull/549)

**Review by Levi-Armstrong — APPROVED** [review]

**Comment by mpowelson** [comment]
@Levi-Armstrong Do you want me to merge this?

**Comment by Levi-Armstrong** [comment]
Sure.

**Pull request merged**
